# Generated by Django 4.0.1 on 2022-04-28 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chairman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact_no', models.CharField(max_length=50)),
                ('house_no', models.CharField(max_length=50)),
                ('full_address', models.CharField(max_length=200)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('vehicle_details', models.CharField(max_length=100)),
                ('pic', models.FileField(default='media/images/no-images.png', upload_to='media/images/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('otp', models.IntegerField(default=459)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('role', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Watchman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('contact_no', models.CharField(max_length=50)),
                ('full_address', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=50)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('pic', models.FileField(default='media/images/no-images.png', upload_to='media/images/')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=500)),
                ('video_file', models.FileField(null=True, upload_to='media/images/videos/', verbose_name='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chairman_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.chairman')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Societymember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('contact_no', models.CharField(max_length=50)),
                ('house_no', models.CharField(max_length=50)),
                ('full_address', models.CharField(max_length=200)),
                ('job_profession', models.CharField(max_length=200)),
                ('job_address', models.CharField(max_length=200)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('vehicle_details', models.CharField(max_length=100)),
                ('pic', models.FileField(default='media/images/no-images.png', upload_to='media/images/images/')),
                ('chairman_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.chairman')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Rentsell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homevehicle_title', models.TextField(max_length=200)),
                ('homevehicle_type', models.TextField(max_length=200)),
                ('homevehicle_rentsell', models.TextField(max_length=200)),
                ('homevehicle_discription', models.TextField(max_length=500)),
                ('homevehicle_contactno', models.CharField(max_length=50)),
                ('homevehicle_budget', models.CharField(max_length=50)),
                ('homevehicle_address_no', models.CharField(max_length=200)),
                ('homevehicle_preowned', models.CharField(max_length=50)),
                ('pic', models.FileField(default='media/images/no-images.png', upload_to='media/images/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.societymember')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_pic', models.FileField(default='media/images/no-images.png', upload_to='media/images/images/')),
                ('pic_name', models.CharField(max_length=50)),
                ('pic_date', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chairman_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.chairman')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_title', models.TextField(max_length=200)),
                ('notice_date', models.DateField(null=True)),
                ('notice_discription', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chairman_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.chairman')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.TextField(default='', max_length=50)),
                ('month', models.TextField(max_length=50)),
                ('amount', models.TextField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chairman_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.chairman')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=50)),
                ('event_date', models.DateField(null=True)),
                ('event_discription', models.TextField(max_length=500)),
                ('event_pic', models.FileField(default='media/images/no-images.png', upload_to='media/images/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chairman_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.chairman')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaints_title', models.TextField(max_length=200)),
                ('complaints_discription', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.societymember')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='chairman',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
    ]
